package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class XsltDebuggerIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, XsltDebuggerIcons.class);
  }

  
  public static class Actions {
    public static final Icon FilterWhitespace = load("/icons/actions/filterWhitespace.png"); // 16x16

  }
  public static final Icon XmlComment = load("/icons/xmlComment.png"); // 16x16
}
